
name: xd

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: rdp
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "FBYt_HuB_2024" -Force)
    - name: GetIp
      run: Get-NetIPAddress
    - name: install zrok
      run: Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v0.4.39/zrok_0.4.39_windows_amd64.tar.gz -OutFile $env:temp\zrok.tar.gz
    - name: extract zip
      run: |
            New-Item -Path "$env:TEMP\zrok" -ItemType Directory -ErrorAction Stop
            tar -xf $env:temp\zrok.tar.gz -C "$env:TEMP\zrok"
            $source = Join-Path -Path $env:TEMP -ChildPath "zrok\zrok.exe"
            $destination = Join-Path -Path $env:USERPROFILE -ChildPath "bin\zrok.exe"
            New-Item -Path $destination -ItemType Directory -ErrorAction SilentlyContinue
            Copy-Item -Path $source -Destination $destination
            $env:path += ";"+$destination
            dir
            zrok version
            zrok enable qOh3pbJqN7yh
            zrok share private --backend-mode tcpTunnel localhost:3389 --headless
